version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JWT_SECRET=sua-chave-secreta-aqui
      - DATABASE_URL=jdbc:postgresql://db:5432/classe360_db
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: classe360_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: classe360_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: